BilibiliVipEmoji::usage="xxx";
BilibiliIndexIcon::usage="xxx";
Begin["`DDOS`"];
VipEmojiReshape[line_]:=Block[
	{drop=KeyDrop[line["emojis"],{"state","remark"}]},
	Append[
		<|"ID"->#["id"],"URL"->#["url"],"Name"->StringTake[#["name"],2;;-2]|>&/@drop,
		<|"ID"->line["pid"],"URL"->line["purl"],"Name"->line["pname"]|>
	]];
BilibiliVipEmoji[]:=Block[
	{get=URLExecute["http://api.bilibili.com/x/v2/reply/emojis","RawJSON"]["data"]},
	BilibiliDownloadObject[<|
		"Date"->Now,
		"Category"->"Bilibili Vip Emoji",
		"Data"->SortBy[Flatten[VipEmojiReshape/@get],"ID"],
		"Path"->FileNameJoin@{$BilibiliLinkData,"Image","Emoji"},
		"Size"->Style["Unknow",Red]
	|>
]];
IndexIconReshape[line_]:=<|
	"ID"->line["id"],
	"Name"->line["title"],
	"URL"->line["icon"]
|>;
BilibiliIndexIcon[]:=Block[
	{get=URLExecute["https://www.bilibili.com/index/index-icon.json","RawJSON"]["fix"]},
	BilibiliDownloadObject[<|
		"Date"->Now,
		"Category"->"Bilibili Index Icon",
		"Data"->SortBy[Flatten[IndexIconReshape/@get],"ID"],
		"Path"->FileNameJoin@{$BilibiliLinkData,"Image","Icon"},
		"Size"->Style["Unknow",Red]
	|>
]];
BilibiliIndexIcon["Raw"]=URLExecute["https://www.bilibili.com/index/index-icon.json","RawJSON"]["fix"];
End[]